DROP DATABASE IF EXISTS bd_apontamentos;
CREATE DATABASE bd_apontamentos;
USE bd_apontamentos;

CREATE TABLE Area (
    ID_Area INT PRIMARY KEY AUTO_INCREMENT,
    NomeArea VARCHAR(100) NOT NULL
);

CREATE TABLE Time (
    ID_Time INT PRIMARY KEY AUTO_INCREMENT,
    NomeTime VARCHAR(100) NOT NULL,
    fk_ID_Area INT NOT NULL
);

CREATE TABLE Usuario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NomeUsuario VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL,
    fk_ID_Time INT NOT NULL
);
 
ALTER TABLE Time ADD CONSTRAINT FK_Time_Area
    FOREIGN KEY (fk_ID_Area)
    REFERENCES Area (ID_Area)
    ON DELETE RESTRICT;

ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Time
    FOREIGN KEY (fk_ID_Time)
    REFERENCES Time (ID_Time)
    ON DELETE RESTRICT;